# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dev_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev',
            name='dev',
        ),
        migrations.AlterField(
            model_name='dev',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
