# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170531_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('picture_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('picture_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_info', models.TextField()),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_auth',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(primary_key=True)),
                ('auth', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_kor', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('playdate', models.DateField()),
                ('playtime', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
                ('nation', models.CharField(max_length=50)),
                ('poster_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('posting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('contents', models.TextField()),
                ('like', models.IntegerField()),
            ],
        ),
    ]
